### ISSUE TITLE
Add a metric to measure "number of open files"

### ISSUE THREAD

**Issue by madeesha** [wso2/performance-apim#25]
**Description:**
APIM gateway shows a large number of open files when running a load test.  Checked the number of open files using, lsof command and sar -v. The results are mentioned below.

output of 'lsof | wc -l' before start the server : 879

output of 'lsof | wc -l' just after start the server : 53590

output of 'lsof | wc -l' when running the load test : 4674652

output of 'lsof -p pid | wc -l' when running the load test : 3969

sar -v output     

06:26:01        56643      1152     66043         2
06:27:01        56643      1120     66043         2
06:28:01        56643      1120     66043         2
06:29:01        56643      1120     66043         2
06:30:01        56643      1152     66043         2
06:31:01        56643      1152     66043         2

**Affected Product Version:** APIM 2.6.0

**OS, DB, other environment details and versions:**    
OS - Ubuntu
DB - PostregeSQL

**Comment by nandika** [comment]
This is expected. 

https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/deployment-best-practices/tuning-performance/
